spring.application.name=ticketsystem
# Kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_db
spring.datasource.username=root
spring.datasource.password=

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# cloudinary
cloudinary.cloud_name=dazvnvjrg
cloudinary.api_key=235521298189635
cloudinary.api_secret=ZomvIlwMLCRRJh8DWnxqqrueCVg

# Cho phép Swagger UI hoạt động
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# =====================================================
# 🏦 SePay Payment Configuration
# =====================================================
# API Key từ SePay (Webhook Secret)
sepay.api.key=JAVA_SPRINGBOOT_SEPAY_8080

# Số tài khoản nhận tiền (VD: MBBank, VietcomBank, etc.)
sepay.api.account-number=0392986255

# Tên tài khoản (sẽ hiển thị trên QR code)
sepay.api.account-name=CINEMA

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=DEBUG

